from __future__ import annotations

from pathlib import Path


APP_NAME = "ap-bizhelper"
USER_AGENT = f"{APP_NAME}/1.0"
USER_AGENT_HEADER = "User-Agent"

HOME_DIR = Path.home()
LOCAL_CONFIG_DIR = HOME_DIR / ".config"
LOCAL_SHARE_DIR = HOME_DIR / ".local" / "share"

CONFIG_DIR = LOCAL_CONFIG_DIR / APP_NAME
DATA_DIR = LOCAL_SHARE_DIR / APP_NAME
LOG_ROOT = DATA_DIR / "logs"
LOG_PREFIX = f"[{APP_NAME}]"

ARCHIPELAGO_CONFIG_DIR = LOCAL_CONFIG_DIR / "Archipelago"
ARCHIPELAGO_DATA_DIR = LOCAL_SHARE_DIR / "Archipelago"
ARCHIPELAGO_WORLDS_DIR = ARCHIPELAGO_DATA_DIR / "worlds"

APPLICATIONS_DIR = LOCAL_SHARE_DIR / "applications"
MIME_PACKAGES_DIR = LOCAL_SHARE_DIR / "mime" / "packages"
BACKUPS_DIR = DATA_DIR / "backups"
GAME_SAVES_DIR = DATA_DIR / "saves"
SAVE_HELPER_STAGED_FILENAME = "save_migration_helper.py"
APP_COMPONENTS_DIR = DATA_DIR / "app_components"
APP_COMPONENTS_PYTHON_DIR = APP_COMPONENTS_DIR / "python"

FILE_FILTER_APWORLD = "*.apworld"
FILE_FILTER_ARCHIVE = "*.zip *.tar.gz"
FILE_FILTER_EXE = "*.exe"
FILE_FILTER_ZIP = "*.zip"

AP_APPIMAGE_DEFAULT = DATA_DIR / "Archipelago.AppImage"
BIZHELPER_APPIMAGE_DEFAULT = DATA_DIR / "ap-bizhelper.AppImage"

AP_APPIMAGE_KEY = "AP_APPIMAGE"
AP_DESKTOP_SHORTCUT_KEY = "AP_DESKTOP_SHORTCUT"
AP_LATEST_SEEN_VERSION_KEY = "AP_LATEST_SEEN_VERSION"
AP_SKIP_VERSION_KEY = "AP_SKIP_VERSION"
AP_VERSION_KEY = "AP_VERSION"
AP_BIZHELPER_CONNECTOR_PATH_ENV = "AP_BIZHELPER_CONNECTOR_PATH"
AP_WAIT_FOR_EXIT_KEY = "AP_WAIT_FOR_EXIT"
AP_WAIT_FOR_EXIT_POLL_SECONDS_KEY = "AP_WAIT_FOR_EXIT_POLL_SECONDS"
BIZHELPER_APPIMAGE_KEY = "BIZHELPER_APPIMAGE"
BIZHAWK_DESKTOP_SHORTCUT_KEY = "BIZHAWK_DESKTOP_SHORTCUT"
BIZHAWK_CLEAR_LD_PRELOAD_KEY = "BIZHAWK_CLEAR_LD_PRELOAD"
BIZHAWK_EXE_KEY = "BIZHAWK_EXE"
BIZHAWK_ENTRY_LUA_PATH_KEY = "BIZHAWK_ENTRY_LUA_PATH"
BIZHAWK_LATEST_SEEN_KEY = "BIZHAWK_LATEST_SEEN_VERSION"
BIZHAWK_INSTALL_DIR_KEY = "BIZHAWK_INSTALL_DIR"
BIZHAWK_LAST_LAUNCH_ARGS_KEY = "BIZHAWK_LAST_LAUNCH_ARGS"
BIZHAWK_LAST_PID_KEY = "BIZHAWK_LAST_PID"
BIZHAWK_RUNNER_KEY = "BIZHAWK_RUNNER"
BIZHAWK_ENTRY_LUA_FILENAME = "ap_bizhelper_migration_launcher.lua"
BIZHAWK_SKIP_VERSION_KEY = "BIZHAWK_SKIP_VERSION"
BIZHAWK_VERSION_KEY = "BIZHAWK_VERSION"
BIZHAWK_RUNTIME_ROOT_KEY = "BIZHAWK_RUNTIME_ROOT"
BIZHAWK_RUNTIME_DOWNLOAD_KEY = "BIZHAWK_RUNTIME_DOWNLOAD"
DOWNLOADS_DIR_KEY = "DOWNLOADS_DIR"
DESKTOP_DIR_KEY = "DESKTOP_DIR"
BIZHAWK_SAVERAM_DIR_KEY = "BIZHAWK_SAVERAM_DIR"
LAST_FILE_DIALOG_DIR_KEY = "LAST_FILE_DIALOG_DIR"
LAST_FILE_DIALOG_DIRS_KEY = "LAST_FILE_DIALOG_DIRS"
LAST_ROM_DIR_KEY = "LAST_ROM_DIR"
ROM_HASH_CACHE_KEY = "ROM_HASH_CACHE"
ROM_ROOTS_KEY = "ROM_ROOTS"
SFC_LUA_PATH_KEY = "SFC_LUA_PATH"
SAVE_MIGRATION_HELPER_PATH_KEY = "SAVE_MIGRATION_HELPER_PATH"
STEAM_APPID_KEY = "STEAM_APPID"
STEAM_ROOT_PATH_KEY = "STEAM_ROOT_PATH"
PENDING_RELAUNCH_ARGS_KEY = "PENDING_RELAUNCH_ARGS"
USE_CACHED_RELAUNCH_ARGS_KEY = "USE_CACHED_RELAUNCH_ARGS"
